### ISSUE TITLE
[EI/MI] No default message builder and formatter configured for content type text/html

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/integration-studio-examples#58]
**Description:**
$subject. Since MI and EI do not support default message builder and formatter for content type `text/html`, users need to add a it manually as shown below.

* In MI, add the following configuration into the conf/deployment.toml
```toml
[[custom_message_formatters]]
content_type = "text/html"
class = "org.apache.axis2.transport.http.ApplicationXMLFormatter"
```

* In EI, comment out the message builder and formatter for the text/html
